### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Kyle-Ye** [winderica/DailyReport#2]
```
npm node-fetch
// create config.json
node main
```
tried it both using config.json and set config directly. But both complain a error following. 
```
➜  DailyReport git:(master) ✗ node main
(node:5164) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Symbol(Request internals)' of null
    at isRequest (/Volumes/MacWorkplace/Github/DailyReport/node_modules/node-fetch/lib/index.js:1152:50)
    at new Request (/Volumes/MacWorkplace/Github/DailyReport/node_modules/node-fetch/lib/index.js:1174:8)
    at /Volumes/MacWorkplace/Github/DailyReport/node_modules/node-fetch/lib/index.js:1403:19
    at new Promise (<anonymous>)
    at fetch (/Volumes/MacWorkplace/Github/DailyReport/node_modules/node-fetch/lib/index.js:1401:9)
    at get (/Volumes/MacWorkplace/Github/DailyReport/main.js:63:49)
    at login (/Volumes/MacWorkplace/Github/DailyReport/main.js:106:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async fuck (/Volumes/MacWorkplace/Github/DailyReport/main.js:263:5)
(node:5164) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5164) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by winderica** [comment]
~~可以报一下node跟node-fetch的版本吗~~  
应该是登录的时候出了问题，你检查一下学号跟密码是不是对的

**Comment by ManiaciaChao** [comment]
I also encountered this several times.
This may be caused by poor server performance at high concurrency, especially when it's noon because everybody has already got up.
A simple loop may help.

```javascript
(async () => {
  while (true) {
    try {
      await fuck();
      console.log("Successfully fxxked!");
      break;
    } catch (err) {
      console.error(err);
      console.log("attempt to fxxk again...");
    }
  }
})();
```

**Comment by winderica** [comment]
我这边偶尔会报`Socket hangs up`的错，单步调试则不会报错，一直都以为是自己网络的问题。这样看要么是服务器性能不行，要么是做了限制。    
while loop不是一个很好的解决办法，因为每一次中断的填报服务端都会产生一张无效的表单。最好是包装一下fetch，里面sleep一段时间。  
但是感觉po主碰到的问题不是这个，大概是我魔改的des出了问题，总之先观望一下

**Comment by Kyle-Ye** [comment]
> ~可以报一下node跟node-fetch的版本吗~
> 应该是登录的时候出了问题，你检查一下学号跟密码是不是对的

```
➜  DailyReport git:(master) ✗ node -v  
v13.8.0

// node-fetch
node-fetch@2.6.0
```
学号和密码没问题，我试试loop先

**Comment by Kyle-Ye** [comment]
我现在也是`Socket hangs up`
```
(node:1491) UnhandledPromiseRejectionWarning: FetchError: request to https://yqtb.hust.edu.cn/infoplus/form/BKS/start failed, reason: socket hang up
    at ClientRequest.<anonymous> (/Volumes/MacWorkplace/Github/DailyReport/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:321:20)
    at TLSSocket.socketOnEnd (_http_client.js:463:9)
    at TLSSocket.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:1491) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1491) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by winderica** [comment]
ok，待会改一下

**Comment by winderica** [comment]
现在应该可以了，还有问题再open

**Comment by ManiaciaChao** [comment]
仍会（看似）随机地抛出`socket hang up`或者`TypeError: Cannot read property 'Symbol(Request internals)' of null`。重复执行脚本即有几率复现。

`TypeError: Cannot read property 'Symbol(Request internals)' of null`说明`fetch(url, opts)`中参数`url`为null，应该是参数`redirect`没拿到。

不清楚后端是否限制操作频率。不过浏览器访问仍有出现请求失败的情况。我的同学今天下午几次手动填表都没成功。**大概率就是服务器的问题**。
