### ISSUE TITLE
Error caused by the new API

### ISSUE THREAD

**Issue by winderica** [winderica/DailyReport#7]
...and `Response` cannot be serialized by `JSON.stringify`
```
(node:4001) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
    at doAction (/path/to/DailyReport/src/index.js:82:59)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async submit (/path/to/DailyReport/src/index.js:90:12)
    at async fuck (/path/to/DailyReport/src/index.js:159:26)
```

**Comment by Enter-tainer** [comment]
🙏👍👍👍❤️
